### ISSUE TITLE
Android build targeting KitKat WEAR?

### ISSUE THREAD

**Issue by tower120** [nventive/Uno.Playground#15]
I think that's by mistake. On Android you targeting KitKat WEAR. Same in Google play market - its for wearable only (I can't install it on my tablet)...

**Comment by MatFillion** [comment]
@tower120 what Android version is your tablet ?

**Comment by tower120** [comment]
Android 4.4

**Comment by MatFillion** [comment]
@tower120 I've set this app to build with the minimum SDK of 21 (Android 5.0), as you mentioned it was wrongly set to a android-wear-specific SDK Level (20), 

It should also work on 4.4, you can change it locally and test on your tablet. You'll need to edit `android:minSdkVersion="21"` in the androidmanifest.xml and change 21 for 19.

**Comment by tower120** [comment]
Why SDK 21 ? Framework not work with lower SDK?

**Comment by MatFillion** [comment]
Uno platform supports 4.4. It's just that we set the minimum SDK for this Gallery app to Android 5.0.
