### ISSUE TITLE
Nuget Packages

### ISSUE THREAD

**Issue by JADSN** [nventive/Uno.Playground#3]
Isn't possible install nuget packages.

![nuget packages](https://user-images.githubusercontent.com/7506354/40115313-62b00794-58e6-11e8-8703-eec4fa135d0b.PNG)

**Comment by jeromelaban** [comment]
Hi @JADSN, thanks for the report.

The uno package is currently published as "pre-release". Can you try checking the box next to the search field, in your screenshot ?

**Comment by JADSN** [comment]
This works.
