### ISSUE TITLE
UWP build error 

### ISSUE THREAD

**Issue by hupo376787** [nventive/Uno.Playground#7]
Solution https://github.com/nventive/Uno/issues/5 not work.

Error		Generation failed for aa. System.AggregateException: One or more errors happened ---> System.InvalidOperationException: The type Windows.UI.Xaml.ElementStub could not be found
   在 ad.c(String A_0)
   在 ad..ctor(ac A_0, String A_1, String A_2, n A_3, String A_4, DateTime A_5, String[] A_6, String[] A_7, Boolean A_8, af A_9, Boolean A_10, Dictionary`2 A_11, Boolean A_12)
   在 z.a.e(ac A_0)
   在 System.Linq.Parallel.SelectQueryOperator`2.SelectQueryOperatorResults.GetElement(Int32 index)
   在 System.Linq.Parallel.QueryResults`1.get_Item(Int32 index)
   在 System.Linq.Parallel.PartitionedDataSource`1.ListContiguousIndexRangeEnumerator.MoveNext(T& currentElement, Int32& currentKey)
   在 System.Linq.Parallel.StopAndGoSpoolingTask`2.SpoolingWork()
   在 System.Linq.Parallel.SpoolingTaskBase.Work()
   在 System.Linq.Parallel.QueryTask.BaseWork(Object unused)
   在 System.Linq.Parallel.QueryTask.<>c.<.cctor>b__10_0(Object o)
   在 System.Threading.Tasks.Task.InnerInvoke()
   在 System.Threading.Tasks.Task.Execute()
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Linq.Parallel.QueryTaskGroupState.QueryEnd(Boolean userInitiatedDispose)
   在 System.Linq.Parallel.SpoolingTask.SpoolStopAndGo[TInputOutput,TIgnoreKey](QueryTaskGroupState groupState, PartitionedStream`2 partitions, SynchronousChannel`1[] channels, TaskScheduler taskScheduler)
   在 System.Linq.Parallel.DefaultMergeHelper`2.System.Linq.Parallel.IMergeHelper<TInputOutput>.Execute()
   在 System.Linq.Parallel.MergeExecutor`1.Execute()
   在 System.Linq.Parallel.MergeExecutor`1.Execute[TKey](PartitionedStream`2 partitions, Boolean ignoreOutput, ParallelMergeOptions options, TaskScheduler taskScheduler, Boolean isOrdered, CancellationState cancellationState, Int32 queryId)
   在 System.Linq.Parallel.PartitionedStreamMerger`1.Receive[TKey](PartitionedStream`2 partitionedStream)
   在 System.Linq.Parallel.UnaryQueryOperator`2.UnaryQueryOperatorResults.GivePartitionedStream(IPartitionedStreamRecipient`1 recipient)
   在 System.Linq.Parallel.QueryOperator`1.GetOpenedEnumerator(Nullable`1 mergeOptions, Boolean suppressOrder, Boolean forEffect, QuerySettings querySettings)
   在 System.Linq.Parallel.QueryOpeningEnumerator`1.OpenQuery()
   在 System.Linq.Parallel.QueryOpeningEnumerator`1.MoveNext()
   在 System.Linq.ParallelEnumerable.ToList[TSource](ParallelQuery`1 source)
   在 z.c()
   在 aa.Execute(SourceGeneratorContext context)
   在 Uno.SourceGeneration.Host.SourceGeneratorHost.<>c__DisplayClass2_0.<Generate>b__13(ValueTuple`2 generatorDef) 位置 C:\projects\uno-sourcegeneration\src\Uno.SourceGenerationHost.Shared\SourceGeneratorHost.cs:行号 150
---> (内部异常 #0) System.InvalidOperationException: The type Windows.UI.Xaml.ElementStub could not be found
   在 ad.c(String A_0)
   在 ad..ctor(ac A_0, String A_1, String A_2, n A_3, String A_4, DateTime A_5, String[] A_6, String[] A_7, Boolean A_8, af A_9, Boolean A_10, Dictionary`2 A_11, Boolean A_12)
   在 z.a.e(ac A_0)
   在 System.Linq.Parallel.SelectQueryOperator`2.SelectQueryOperatorResults.GetElement(Int32 index)
   在 System.Linq.Parallel.QueryResults`1.get_Item(Int32 index)
   在 System.Linq.Parallel.PartitionedDataSource`1.ListContiguousIndexRangeEnumerator.MoveNext(T& currentElement, Int32& currentKey)
   在 System.Linq.Parallel.StopAndGoSpoolingTask`2.SpoolingWork()
   在 System.Linq.Parallel.SpoolingTaskBase.Work()
   在 System.Linq.Parallel.QueryTask.BaseWork(Object unused)
   在 System.Linq.Parallel.QueryTask.<>c.<.cctor>b__10_0(Object o)
   在 System.Threading.Tasks.Task.InnerInvoke()
   在 System.Threading.Tasks.Task.Execute()<---

---> (内部异常 #1) System.InvalidOperationException: The type Windows.UI.Xaml.ElementStub could not be found
   在 ad.c(String A_0)
   在 ad..ctor(ac A_0, String A_1, String A_2, n A_3, String A_4, DateTime A_5, String[] A_6, String[] A_7, Boolean A_8, af A_9, Boolean A_10, Dictionary`2 A_11, Boolean A_12)
   在 z.a.e(ac A_0)
   在 System.Linq.Parallel.SelectQueryOperator`2.SelectQueryOperatorResults.GetElement(Int32 index)
   在 System.Linq.Parallel.QueryResults`1.get_Item(Int32 index)
   在 System.Linq.Parallel.PartitionedDataSource`1.ListContiguousIndexRangeEnumerator.MoveNext(T& currentElement, Int32& currentKey)
   在 System.Linq.Parallel.StopAndGoSpoolingTask`2.SpoolingWork()
   在 System.Linq.Parallel.SpoolingTaskBase.Work()
   在 System.Linq.Parallel.QueryTask.BaseWork(Object unused)
   在 System.Linq.Parallel.QueryTask.<>c.<.cctor>b__10_0(Object o)
   在 System.Threading.Tasks.Task.InnerInvoke()
   在 System.Threading.Tasks.Task.Execute()<---

---> (内部异常 #2) System.InvalidOperationException: The type Windows.UI.Xaml.ElementStub could not be found
   在 ad.c(String A_0)
   在 ad..ctor(ac A_0, String A_1, String A_2, n A_3, String A_4, DateTime A_5, String[] A_6, String[] A_7, Boolean A_8, af A_9, Boolean A_10, Dictionary`2 A_11, Boolean A_12)
   在 z.a.e(ac A_0)
   在 System.Linq.Parallel.SelectQueryOperator`2.SelectQueryOperatorResults.GetElement(Int32 index)
   在 System.Linq.Parallel.QueryResults`1.get_Item(Int32 index)
   在 System.Linq.Parallel.PartitionedDataSource`1.ListContiguousIndexRangeEnumerator.MoveNext(T& currentElement, Int32& currentKey)
   在 System.Linq.Parallel.StopAndGoSpoolingTask`2.SpoolingWork()
   在 System.Linq.Parallel.SpoolingTaskBase.Work()
   在 System.Linq.Parallel.QueryTask.BaseWork(Object unused)
   在 System.Linq.Parallel.QueryTask.<>c.<.cctor>b__10_0(Object o)
   在 System.Threading.Tasks.Task.InnerInvoke()
   在 System.Threading.Tasks.Task.Execute()<---

---> (内部异常 #3) System.InvalidOperationException: The type Windows.UI.Xaml.ElementStub could not be found
   在 ad.c(String A_0)
   在 ad..ctor(ac A_0, String A_1, String A_2, n A_3, String A_4, DateTime A_5, String[] A_6, String[] A_7, Boolean A_8, af A_9, Boolean A_10, Dictionary`2 A_11, Boolean A_12)
   在 z.a.e(ac A_0)
   在 System.Linq.Parallel.SelectQueryOperator`2.SelectQueryOperatorResults.GetElement(Int32 index)
   在 System.Linq.Parallel.QueryResults`1.get_Item(Int32 index)
   在 System.Linq.Parallel.PartitionedDataSource`1.ListContiguousIndexRangeEnumerator.MoveNext(T& currentElement, Int32& currentKey)
   在 System.Linq.Parallel.StopAndGoSpoolingTask`2.SpoolingWork()
   在 System.Linq.Parallel.SpoolingTaskBase.Work()
   在 System.Linq.Parallel.QueryTask.BaseWork(Object unused)
   在 System.Linq.Parallel.QueryTask.<>c.<.cctor>b__10_0(Object o)
   在 System.Threading.Tasks.Task.InnerInvoke()
   在 System.Threading.Tasks.Task.Execute()<---

---> (内部异常 #4) System.InvalidOperationException: The type Windows.UI.Xaml.ElementStub could not be found
   在 ad.c(String A_0)
   在 ad..ctor(ac A_0, String A_1, String A_2, n A_3, String A_4, DateTime A_5, String[] A_6, String[] A_7, Boolean A_8, af A_9, Boolean A_10, Dictionary`2 A_11, Boolean A_12)
   在 z.a.e(ac A_0)
   在 System.Linq.Parallel.SelectQueryOperator`2.SelectQueryOperatorResults.GetElement(Int32 index)
   在 System.Linq.Parallel.QueryResults`1.get_Item(Int32 index)
   在 System.Linq.Parallel.PartitionedDataSource`1.ListContiguousIndexRangeEnumerator.MoveNext(T& currentElement, Int32& currentKey)
   在 System.Linq.Parallel.StopAndGoSpoolingTask`2.SpoolingWork()
   在 System.Linq.Parallel.SpoolingTaskBase.Work()
   在 System.Linq.Parallel.QueryTask.BaseWork(Object unused)
   在 System.Linq.Parallel.QueryTask.<>c.<.cctor>b__10_0(Object o)
   在 System.Threading.Tasks.Task.InnerInvoke()
   在 System.Threading.Tasks.Task.Execute()<---

---> (内部异常 #5) System.InvalidOperationException: The type Windows.UI.Xaml.ElementStub could not be found
   在 ad.c(String A_0)
   在 ad..ctor(ac A_0, String A_1, String A_2, n A_3, String A_4, DateTime A_5, String[] A_6, String[] A_7, Boolean A_8, af A_9, Boolean A_10, Dictionary`2 A_11, Boolean A_12)
   在 z.a.e(ac A_0)
   在 System.Linq.Parallel.SelectQueryOperator`2.SelectQueryOperatorResults.GetElement(Int32 index)
   在 System.Linq.Parallel.QueryResults`1.get_Item(Int32 index)
   在 System.Linq.Parallel.PartitionedDataSource`1.ListContiguousIndexRangeEnumerator.MoveNext(T& currentElement, Int32& currentKey)
   在 System.Linq.Parallel.StopAndGoSpoolingTask`2.SpoolingWork()
   在 System.Linq.Parallel.SpoolingTaskBase.Work()
   在 System.Linq.Parallel.QueryTask.BaseWork(Object unused)
   在 System.Linq.Parallel.QueryTask.RunTaskSynchronously(Object o)
   在 System.Threading.Tasks.Task.InnerInvoke()
   在 System.Threading.Tasks.Task.Execute()<---

---> (内部异常 #6) System.InvalidOperationException: The type Windows.UI.Xaml.ElementStub could not be found
   在 ad.c(String A_0)
   在 ad..ctor(ac A_0, String A_1, String A_2, n A_3, String A_4, DateTime A_5, String[] A_6, String[] A_7, Boolean A_8, af A_9, Boolean A_10, Dictionary`2 A_11, Boolean A_12)
   在 z.a.e(ac A_0)
   在 System.Linq.Parallel.SelectQueryOperator`2.SelectQueryOperatorResults.GetElement(Int32 index)
   在 System.Linq.Parallel.QueryResults`1.get_Item(Int32 index)
   在 System.Linq.Parallel.PartitionedDataSource`1.ListContiguousIndexRangeEnumerator.MoveNext(T& currentElement, Int32& currentKey)
   在 System.Linq.Parallel.StopAndGoSpoolingTask`2.SpoolingWork()
   在 System.Linq.Parallel.SpoolingTaskBase.Work()
   在 System.Linq.Parallel.QueryTask.BaseWork(Object unused)
   在 System.Linq.Parallel.QueryTask.<>c.<.cctor>b__10_0(Object o)
   在 System.Threading.Tasks.Task.InnerInvoke()
   在 System.Threading.Tasks.Task.Execute()<---

---> (内部异常 #7) System.InvalidOperationException: The type Windows.UI.Xaml.ElementStub could not be found
   在 ad.c(String A_0)
   在 ad..ctor(ac A_0, String A_1, String A_2, n A_3, String A_4, DateTime A_5, String[] A_6, String[] A_7, Boolean A_8, af A_9, Boolean A_10, Dictionary`2 A_11, Boolean A_12)
   在 z.a.e(ac A_0)
   在 System.Linq.Parallel.SelectQueryOperator`2.SelectQueryOperatorResults.GetElement(Int32 index)
   在 System.Linq.Parallel.QueryResults`1.get_Item(Int32 index)
   在 System.Linq.Parallel.PartitionedDataSource`1.ListContiguousIndexRangeEnumerator.MoveNext(T& currentElement, Int32& currentKey)
   在 System.Linq.Parallel.StopAndGoSpoolingTask`2.SpoolingWork()
   在 System.Linq.Parallel.SpoolingTaskBase.Work()
   在 System.Linq.Parallel.QueryTask.BaseWork(Object unused)
   在 System.Linq.Parallel.QueryTask.<>c.<.cctor>b__10_0(Object o)
   在 System.Threading.Tasks.Task.InnerInvoke()
   在 System.Threading.Tasks.Task.Execute()<---	Uno.UI.Demo.UWP

**Comment by carldebilly** [comment]
This is usually happening when you have a Non-panel element with more than one children in the xaml.

**Comment by jeromelaban** [comment]
This is actually caused by https://github.com/nventive/Uno/issues/5.

You need to update the Uno.UI package to the latest available version, this will fix the UWP build issue.

**Comment by hupo376787** [comment]
Hi, there. Actually, mine are the latest package.  I just downloaded the zip from this repo.
![image](https://user-images.githubusercontent.com/14960168/40974359-e99a0c78-68f9-11e8-9519-0d78520113a7.png)

**Comment by jeromelaban** [comment]
@hupo376787 this is interesting. You should be seeing [1.31.0-dev.8](https://www.nuget.org/packages/Uno.UI/1.31.0-dev.8). Can you make sure to clear your nuget cache ?

**Comment by hupo376787** [comment]
Hi, I found the reason.  The package source is set to "Local cache" when I unzip the sln. I changed to all, then 1.31.3-dev.8 comes.
Thx.
![image](https://user-images.githubusercontent.com/14960168/40975045-33f0e402-68fc-11e8-8033-f6353f291c81.png)
